### PR TITLE
tests: add federation tests to project

### PR DESCRIPTION
**Pull request by kieckhafer**
Using `federation-testing-tool`, adds testing of the federated gateway.

1. Unit tests for an isolated service
1. Unit tests for multiple services

## Testing
`npm run test` locally

### CODE REVIEW

**Comment by aldeed** [comment]
@kieckhafer Can this be reviewed and merged now?

**Comment by kieckhafer** [comment]
@aldeed yes, the blocker has been merged, this can be reviewed.

**Review by aldeed — APPROVED** [review]

**Comment by aldeed** [comment]
@rosshadden This seems fine to me. Okay to merge?

**Review by rosshadden — APPROVED** [review]

**Comment by rosshadden** [comment]
👍

**Comment by aldeed** [comment]
@kieckhafer @rosshadden It appears I do not have a merge button on this repo. Can you merge?

**Pull request merged**
